language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: SYMFONY_VERSION="^2.7"
        - php: 5.6
          env: SYMFONY_VERSION="^2.8"
        - php: 7.0
          env: SYMFONY_VERSION="^3.0"

before_install:
    - 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;'

install:
    - composer install --prefer-source --no-interaction --no-progress

script:
    - composer test

notifications:
    email: false